# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_pergunta_alternativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
